spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
      enabled: true
  profiles:
    include: dbsource,cloud
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.study.blog.domain, com.study.blog.dto
  mapper-locations: classpath:mybatis/mapper/*.xml
logging:
  level:
    web: info


