spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: java
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
      enabled: true
  profiles:
    include: oauth

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.study.blog.domain, com.study.blog.dto
  mapper-locations: classpath:mybatis/mapper/*.xml
logging:
  level:
    web: debug


